courses:
  - path: ./4850_AdvancedFE/2025-fall-alex/modules/
    name: Adv Frontend
  - path: ./1420/2025-fall-alex/modules/
    name: "1420"
  - path: ./1810/2025-fall-alex/modules/
    name: Web Intro
  - path: ./1430/2025-fall-alex/modules/
    name: UX
  - path: ./1425/2025-fall-alex/modules/
    name: "1425"
  - path: ./4850_AdvancedFE/2026-spring-alex/modules
    name: Adv Frontend Spring
  - path: ./1400/2026_spring_alex/modules
    name: "1400"
  - path: ./1405/2026_spring_alex
    name: "1405"
  - path: ./1810/2026-spring-alex/modules
    name: Web Intro Spring
  - path: ./3840_Telemetry/2026_spring_alex
    name: Telem and Ops New
  - path: ./4620_Distributed/2026-spring-alex/modules
    name: Distributed
